version: 2

templates:
    - &default-docker-image
        docker:
        - image: sociomantictsunami/dlang:xenial-v3
          user: cachalot
    - &test-template
        <<: *default-docker-image
        steps:
        - checkout
        - run:
            name: Update submodules
            command: |
                git submodule sync
                git submodule update --init
        - run:
            name: Install dependencies
            command: sudo -E .circleci/deps.sh
        - run:
            name: Build & run tests
            command: .circleci/test.sh
        - run:
            name: Upload code coverage report
            command: bash <(curl -s https://codecov.io/bash)
    - &workflow-job-template
        filters:
            tags:
                ignore: /.*\+d2$/

workflows:
    version: 2
    all:
        jobs:
        - test-1.082-devel: *workflow-job-template
        - test-1.082-prod: *workflow-job-template
        - test-2.070-devel: *workflow-job-template
        - test-2.070-prod: *workflow-job-template
        - test-2.071-devel: *workflow-job-template
        - test-2.071-prod: *workflow-job-template
        - test-2.078-upstream-devel: *workflow-job-template
        - test-2.078-upstream-prod: *workflow-job-template
        - d2tag:
            context: org-global
            requires:
            - test-1.082-devel
            - test-1.082-prod
            - test-2.070-devel
            - test-2.070-prod
            - test-2.071-devel
            - test-2.071-prod
            - test-2.078-upstream-devel
            - test-2.078-upstream-prod
            filters:
                tags:
                    ignore: /.*\+d2$/
                branches:
                    ignore: /.*/

jobs:
    test-1.082-devel:
        <<: *test-template
        environment:
        - DMD: "1.082.*"
        - F: "devel"
    test-1.082-prod:
        <<: *test-template
        environment:
        - DMD: "1.082.*"
        - F: "production"
    test-2.070-devel:
        <<: *test-template
        environment:
        - DMD: "2.070.2.s*"
        - F: "devel"
    test-2.070-prod:
        <<: *test-template
        environment:
        - DMD: "2.070.2.s*"
        - F: "production"
    test-2.071-devel:
        <<: *test-template
        environment:
        - DMD: "2.071.2.s*"
        - F: "devel"
    test-2.071-prod:
        <<: *test-template
        environment:
        - DMD: "2.071.2.s*"
        - F: "production"
    test-2.078-upstream-devel:
        <<: *test-template
        environment:
        - DMD: "2.078.*"
        - F: "devel"
    test-2.078-upstream-prod:
        <<: *test-template
        environment:
        - DMD: "2.078.*"
        - F: "production"
    d2tag:
        <<: *default-docker-image
        steps:
        - checkout
        - run:
            name: Update submodules
            command: |
                git submodule sync
                git submodule update --init
        - run: make d2conv
        - run: .circleci/d2tag.sh
